# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180822_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_image', null=True, upload_to='', width_field='width_image'),
        ),
    ]
